pub mod detection;
pub mod exports;
mod graph;
mod propagation;
pub mod registry;

// Generic name prefixes that should not be used as module names.
// These are generated by the decompiler and do not carry semantic meaning.
pub(crate) const GENERIC_NAME_PREFIXES: &[&str] = &[
    "tmp", "closure_", "fnResult", "arg", "module_",
    "_interopRequire", "_interopDefault", "_interopNamespace",
    // Metro factory role names get a `_` prefix when they collide with a
    // builtin/reserved word during register naming, and are deduped to
    // `_module`, `_module1`, `_exports2`, …, none are real module names.
    "_module", "_exports", "_require", "_global", "_dependencyMap",
    "_importDefault", "_importAll",
];

// Exact generic names that should not be used as module names.
pub(crate) const GENERIC_EXACT_NAMES: &[&str] = &[
    "default", "_default", "undefined", "null", "true", "false",
    "item", "self", "key", "value", "merged",
    "exports", "wrapper", "require", "anonymous", "global",
    "__esModule", "module", "dependencyMap",
    // Metro factory parameter role names (and their reserved-word-escaped
    // `_`-prefixed forms) must never be mistaken for a module's own name.
    "_module", "_exports", "_require", "_global", "_dependencyMap",
    "importDefault", "importAll", "_importDefault", "_importAll",
    "Object", "Object2", "Object3", "Array", "Array2", "Array3",
    "num", "str", "val", "res",
];

// Check if a name is obviously generic (decompiler-generated, too vague, or a common placeholder).
//
// This is the shared core used by both `detection::is_meaningful_name()` and
// `propagation::is_meaningful_require_name()`. Each caller adds its own
// additional checks (e.g., `f1234` pattern, register patterns, length checks).
pub(crate) fn is_obviously_generic(name: &str) -> bool {
    // Reject exact matches from shared list
    if GENERIC_EXACT_NAMES.contains(&name) { return true; }
    // Reject generic prefixes from shared list
    if GENERIC_NAME_PREFIXES.iter().any(|p| name.starts_with(p)) { return true; }
    // Reject decompiler-generated *Result names (fnResult, fn2Result, definePropertyResult, etc.)
    if name.ends_with("Result") { return true; }
    // Reject register or type role names with an optional numeric suffix, for any
    // number of digits: obj, obj2, obj129, arr5, items9, set7, fn3, num2, str1.
    // The suffix count is unbounded since same-role registers are numbered without
    // a cap, so a fixed length check (obj up to obj99) let obj129 slip through and
    // leak as a module name. A real word keeps its non-digit tail (object, arrow,
    // items list keys, settings) and is not rejected.
    if is_role_name_with_digits(name) { return true; }
    false
}

// True when `name` is a register/type role base followed by nothing or only
// digits (`obj`, `arr129`), the shape the register namer produces for anonymous
// values. A base followed by letters (`object`, `arrow`, `settings`) is a real
// name and returns false.
fn is_role_name_with_digits(name: &str) -> bool {
    const ROLE_BASES: &[&str] = &[
        "obj", "arr", "items", "item", "set", "list", "map",
        "fn", "num", "str", "val", "bool", "res", "el",
    ];
    for base in ROLE_BASES {
        if let Some(rest) = name.strip_prefix(base) {
            if rest.is_empty() || rest.bytes().all(|b| b.is_ascii_digit()) {
                return true;
            }
        }
    }
    false
}

pub use detection::MetroDetector;
pub use graph::{DependencyGraph, DependencyTree};
pub use propagation::{propagate_module_names, rewrite_dependency_maps_late};
pub(crate) use propagation::propagate_module_names_to_closures;
pub use registry::{FactoryRoles, MetroModule, MetroRegistry};

// Helper to expose analyze as a static method on MetroRegistry for compatibility
impl MetroRegistry {
    pub fn analyze(statements: &[crate::ir::Statement]) -> Self {
        let mut registry = Self::new();
        MetroDetector::analyze_statements(statements, &mut registry, &std::collections::HashMap::new());
        registry
    }

    pub fn analyze_statements(&mut self, statements: &[crate::ir::Statement]) {
        MetroDetector::analyze_statements(statements, self, &std::collections::HashMap::new());
    }

    // Variant that supplies factory parameter counts (function_id -> declared
    // param count, this-excluded) so module roles match the Metro convention.
    pub fn analyze_statements_with_params(
        &mut self,
        statements: &[crate::ir::Statement],
        param_counts: &std::collections::HashMap<u32, u32>,
    ) {
        MetroDetector::analyze_statements(statements, self, param_counts);
    }
}

// Re-expose Graph methods on Registry for compatibility if needed,
// OR refactor callers to use DependencyGraph directly.
// For now, let's keep the extension methods or just use the new API.
// To match original API:
impl MetroRegistry {
    pub fn get_dependency_tree(&self, module_id: u32, max_depth: usize) -> DependencyTree {
        DependencyGraph::get_dependency_tree(self, module_id, max_depth)
    }
}

#[cfg(test)]
mod generic_name_tests {
    use super::is_obviously_generic;
    #[test]
    fn rejects_role_names_with_any_digit_count() {
        for n in ["obj", "obj2", "obj129", "items9", "set7", "arr12", "fn3", "num2", "str1", "val0", "map", "list5", "res4"] {
            assert!(is_obviously_generic(n), "{n} should be generic");
        }
    }
    #[test]
    fn keeps_real_words() {
        for n in ["object", "objectPool", "arrow", "settings", "mapper", "result", "response", "listener", "items_list", "numbers", "string2Value"] {
            assert!(!is_obviously_generic(n), "{n} should be kept");
        }
    }
}
