pub mod detection;
pub mod exports;
mod graph;
mod propagation;
pub mod registry;

// Generic name prefixes that should not be used as module names.
// These are generated by the decompiler and do not carry semantic meaning.
pub(crate) const GENERIC_NAME_PREFIXES: &[&str] = &[
    "tmp", "closure_", "fnResult", "arg", "module_",
    "_interopRequire", "_interopDefault", "_interopNamespace",
];

// Exact generic names that should not be used as module names.
pub(crate) const GENERIC_EXACT_NAMES: &[&str] = &[
    "default", "_default", "undefined", "null", "true", "false",
    "item", "self", "key", "value", "merged",
    "exports", "wrapper", "require", "anonymous", "global",
    "__esModule", "module", "dependencyMap",
    "Object", "Object2", "Object3", "Array", "Array2", "Array3",
    "num", "str", "val", "res",
];

// Check if a name is obviously generic (decompiler-generated, too vague, or a common placeholder).
//
// This is the shared core used by both `detection::is_meaningful_name()` and
// `propagation::is_meaningful_require_name()`. Each caller adds its own
// additional checks (e.g., `f1234` pattern, register patterns, length checks).
pub(crate) fn is_obviously_generic(name: &str) -> bool {
    // Reject exact matches from shared list
    if GENERIC_EXACT_NAMES.contains(&name) { return true; }
    // Reject generic prefixes from shared list
    if GENERIC_NAME_PREFIXES.iter().any(|p| name.starts_with(p)) { return true; }
    // Reject decompiler-generated *Result names (fnResult, fn2Result, definePropertyResult, etc.)
    if name.ends_with("Result") { return true; }
    false
}

pub use detection::MetroDetector;
pub use graph::{DependencyGraph, DependencyTree};
pub use propagation::propagate_module_names;
pub use registry::{FactoryRoles, MetroModule, MetroRegistry};

// Helper to expose analyze as a static method on MetroRegistry for compatibility
impl MetroRegistry {
    pub fn analyze(statements: &[crate::ir::Statement]) -> Self {
        let mut registry = Self::new();
        MetroDetector::analyze_statements(statements, &mut registry);
        registry
    }

    pub fn analyze_statements(&mut self, statements: &[crate::ir::Statement]) {
        MetroDetector::analyze_statements(statements, self);
    }
}

// Re-expose Graph methods on Registry for compatibility if needed,
// OR refactor callers to use DependencyGraph directly.
// For now, let's keep the extension methods or just use the new API.
// To match original API:
impl MetroRegistry {
    pub fn get_dependency_tree(&self, module_id: u32, max_depth: usize) -> DependencyTree {
        DependencyGraph::get_dependency_tree(self, module_id, max_depth)
    }
}
